# TCL File Generated by Component Editor 21.1
# Wed Sep 08 15:27:46 CEST 2021
# DO NOT MODIFY


# 
# phy2sys "phy2sys" v1.0
# Herve Echelard 2021.09.08.15:27:46
# 
# 

# 
# request TCL package from ACDS 21.1
# 
package require -exact qsys 21.1


# 
# module phy2sys
# 
set_module_property DESCRIPTION ""
set_module_property NAME phy2sys
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Orolia
set_module_property AUTHOR "Herve Echelard"
set_module_property DISPLAY_NAME phy2sys
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL phy2sys
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file phy2sys.vhd VHDL PATH phy2sys.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressGroup 0
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 bridgedAddressOffset ""
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 minimumResponseLatency 1
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 transparentBridge false
set_interface_property avalon_slave_0 waitrequestAllowance 0
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave_0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port avalon_slave_0 ADR_I address Input 8
add_interface_port avalon_slave_0 RD_I read Input 1
add_interface_port avalon_slave_0 WE_I write Input 1
add_interface_port avalon_slave_0 DAT_I writedata Input 32
add_interface_port avalon_slave_0 DAT_O readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""
set_interface_property clock_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_sink CLK_CPU_I clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_sink RST_CPU_I reset Input 1


# 
# connection point clock_200mhz
# 
add_interface clock_200mhz clock end
set_interface_property clock_200mhz ENABLED true
set_interface_property clock_200mhz EXPORT_OF ""
set_interface_property clock_200mhz PORT_NAME_MAP ""
set_interface_property clock_200mhz CMSIS_SVD_VARIABLES ""
set_interface_property clock_200mhz SVD_ADDRESS_GROUP ""
set_interface_property clock_200mhz IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_200mhz CLK200_I clk Input 1


# 
# connection point rst_200mhz
# 
add_interface rst_200mhz reset end
set_interface_property rst_200mhz associatedClock clock_sink
set_interface_property rst_200mhz synchronousEdges DEASSERT
set_interface_property rst_200mhz ENABLED true
set_interface_property rst_200mhz EXPORT_OF ""
set_interface_property rst_200mhz PORT_NAME_MAP ""
set_interface_property rst_200mhz CMSIS_SVD_VARIABLES ""
set_interface_property rst_200mhz SVD_ADDRESS_GROUP ""
set_interface_property rst_200mhz IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rst_200mhz RST200_I reset Input 1


# 
# connection point PPS_OUT
# 
add_interface PPS_OUT conduit end
set_interface_property PPS_OUT associatedClock clock_sink
set_interface_property PPS_OUT associatedReset ""
set_interface_property PPS_OUT ENABLED true
set_interface_property PPS_OUT EXPORT_OF ""
set_interface_property PPS_OUT PORT_NAME_MAP ""
set_interface_property PPS_OUT CMSIS_SVD_VARIABLES ""
set_interface_property PPS_OUT SVD_ADDRESS_GROUP ""
set_interface_property PPS_OUT IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port PPS_OUT PPS_OUT pps_out Output 1


# 
# connection point time_clock
# 
add_interface time_clock conduit end
set_interface_property time_clock associatedClock clock_200mhz
set_interface_property time_clock associatedReset rst_200mhz
set_interface_property time_clock ENABLED true
set_interface_property time_clock EXPORT_OF ""
set_interface_property time_clock PORT_NAME_MAP ""
set_interface_property time_clock CMSIS_SVD_VARIABLES ""
set_interface_property time_clock SVD_ADDRESS_GROUP ""
set_interface_property time_clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port time_clock TIME_S_O time_s_o Output 32
add_interface_port time_clock TIME_NS_O time_ns_o Output 32

