# TCL File Generated by Component Editor 20.4
# Tue Apr 27 19:20:22 CEST 2021
# DO NOT MODIFY


# 
# pcie_irq_msi "pcie_irq_msi" v1.0
# H ECHELARD 2021.04.27.19:20:22
# 
# 

# 
# request TCL package from ACDS 20.4
# 
package require -exact qsys 20.4


# 
# module pcie_irq_msi
# 
set_module_property DESCRIPTION ""
set_module_property NAME pcie_irq_msi
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Orolia
set_module_property AUTHOR "H ECHELARD"
set_module_property DISPLAY_NAME pcie_irq_msi
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pcie_irq_msi
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pcie_irq_msi.vhd VHDL PATH pcie_irq_msi.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""
set_interface_property clock_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_sink CLK_I clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_sink RST_I reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressGroup 0
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock_sink
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master minimumResponseLatency 1
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master waitrequestAllowance 0
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""
set_interface_property avalon_master IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port avalon_master TXS_WRITE_O write Output 1
add_interface_port avalon_master TXS_ADDRESS_O address Output 32
add_interface_port avalon_master TXS_WRITEDATA_O writedata Output 64
add_interface_port avalon_master TXS_BYTEENABLE_O byteenable Output 8
add_interface_port avalon_master TXS_WAITREQUEST_I waitrequest Input 1


# 
# connection point interrupt_receiver
# 
add_interface interrupt_receiver interrupt start
set_interface_property interrupt_receiver associatedClock clock_sink
set_interface_property interrupt_receiver associatedReset reset_sink
set_interface_property interrupt_receiver irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver ENABLED true
set_interface_property interrupt_receiver EXPORT_OF ""
set_interface_property interrupt_receiver PORT_NAME_MAP ""
set_interface_property interrupt_receiver CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_receiver SVD_ADDRESS_GROUP ""
set_interface_property interrupt_receiver IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port interrupt_receiver IRQ_I irq Input 16


# 
# connection point msi_intfc
# 
add_interface msi_intfc conduit end
set_interface_property msi_intfc associatedClock ""
set_interface_property msi_intfc associatedReset ""
set_interface_property msi_intfc ENABLED true
set_interface_property msi_intfc EXPORT_OF ""
set_interface_property msi_intfc PORT_NAME_MAP ""
set_interface_property msi_intfc CMSIS_SVD_VARIABLES ""
set_interface_property msi_intfc SVD_ADDRESS_GROUP ""
set_interface_property msi_intfc IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port msi_intfc MSIINTFC_I msi_intfc Input 82


# 
# connection point msix_intfc
# 
add_interface msix_intfc conduit end
set_interface_property msix_intfc associatedClock ""
set_interface_property msix_intfc associatedReset ""
set_interface_property msix_intfc ENABLED true
set_interface_property msix_intfc EXPORT_OF ""
set_interface_property msix_intfc PORT_NAME_MAP ""
set_interface_property msix_intfc CMSIS_SVD_VARIABLES ""
set_interface_property msix_intfc SVD_ADDRESS_GROUP ""
set_interface_property msix_intfc IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port msix_intfc MSIXINTFC_I msix_intfc Input 16


# 
# connection point intx_intfc
# 
add_interface intx_intfc conduit end
set_interface_property intx_intfc associatedClock ""
set_interface_property intx_intfc associatedReset ""
set_interface_property intx_intfc ENABLED true
set_interface_property intx_intfc EXPORT_OF ""
set_interface_property intx_intfc PORT_NAME_MAP ""
set_interface_property intx_intfc CMSIS_SVD_VARIABLES ""
set_interface_property intx_intfc SVD_ADDRESS_GROUP ""
set_interface_property intx_intfc IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port intx_intfc INTXREQ_O intx_req Output 1
add_interface_port intx_intfc INTXACK_I intx_ack Input 1

