# TCL File Generated by Component Editor 21.1
# Wed Apr 06 14:13:31 CEST 2022
# DO NOT MODIFY


# 
# PPS_Output_Ctrl "PPS_Output_Ctrl" v1.0
# Herve Echelard 2022.04.06.14:13:31
# 
# 

# 
# request TCL package from ACDS 21.1
# 
package require -exact qsys 21.1


# 
# module PPS_Output_Ctrl
# 
set_module_property DESCRIPTION ""
set_module_property NAME PPS_Output_Ctrl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Orolia
set_module_property AUTHOR "Herve Echelard"
set_module_property DISPLAY_NAME PPS_Output_Ctrl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pps_out_ctrl
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pps_out_ctrl.vhd VHDL PATH pps_out_ctrl.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter PPS_DELAY_200 STD_LOGIC_VECTOR 35 ""
set_parameter_property PPS_DELAY_200 DEFAULT_VALUE 35
set_parameter_property PPS_DELAY_200 DISPLAY_NAME PPS_DELAY_200
set_parameter_property PPS_DELAY_200 WIDTH 32
set_parameter_property PPS_DELAY_200 UNITS None
set_parameter_property PPS_DELAY_200 DESCRIPTION ""
set_parameter_property PPS_DELAY_200 AFFECTS_GENERATION false
set_parameter_property PPS_DELAY_200 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressGroup 0
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_cpu
set_interface_property avalon_slave_0 associatedReset reset_cpu
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 bridgedAddressOffset ""
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 minimumResponseLatency 1
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 transparentBridge false
set_interface_property avalon_slave_0 waitrequestAllowance 0
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave_0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port avalon_slave_0 ADR_I address Input 8
add_interface_port avalon_slave_0 RD_I read Input 1
add_interface_port avalon_slave_0 WE_I write Input 1
add_interface_port avalon_slave_0 DAT_I writedata Input 32
add_interface_port avalon_slave_0 DAT_O readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point rst_200mhz
# 
add_interface rst_200mhz reset end
set_interface_property rst_200mhz associatedClock clock_200mhz
set_interface_property rst_200mhz synchronousEdges DEASSERT
set_interface_property rst_200mhz ENABLED true
set_interface_property rst_200mhz EXPORT_OF ""
set_interface_property rst_200mhz PORT_NAME_MAP ""
set_interface_property rst_200mhz CMSIS_SVD_VARIABLES ""
set_interface_property rst_200mhz SVD_ADDRESS_GROUP ""
set_interface_property rst_200mhz IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rst_200mhz RST200_I reset Input 1


# 
# connection point clock_200mhz
# 
add_interface clock_200mhz clock end
set_interface_property clock_200mhz ENABLED true
set_interface_property clock_200mhz EXPORT_OF ""
set_interface_property clock_200mhz PORT_NAME_MAP ""
set_interface_property clock_200mhz CMSIS_SVD_VARIABLES ""
set_interface_property clock_200mhz SVD_ADDRESS_GROUP ""
set_interface_property clock_200mhz IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_200mhz CLK200_I clk Input 1


# 
# connection point clock_cpu
# 
add_interface clock_cpu clock end
set_interface_property clock_cpu ENABLED true
set_interface_property clock_cpu EXPORT_OF ""
set_interface_property clock_cpu PORT_NAME_MAP ""
set_interface_property clock_cpu CMSIS_SVD_VARIABLES ""
set_interface_property clock_cpu SVD_ADDRESS_GROUP ""
set_interface_property clock_cpu IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_cpu CLK_CPU_I clk Input 1


# 
# connection point reset_cpu
# 
add_interface reset_cpu reset end
set_interface_property reset_cpu associatedClock clock_cpu
set_interface_property reset_cpu synchronousEdges DEASSERT
set_interface_property reset_cpu ENABLED true
set_interface_property reset_cpu EXPORT_OF ""
set_interface_property reset_cpu PORT_NAME_MAP ""
set_interface_property reset_cpu CMSIS_SVD_VARIABLES ""
set_interface_property reset_cpu SVD_ADDRESS_GROUP ""
set_interface_property reset_cpu IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_cpu RST_CPU_I reset Input 1


# 
# connection point irq_pps
# 
add_interface irq_pps interrupt end
set_interface_property irq_pps associatedClock clock_200mhz
set_interface_property irq_pps associatedReset rst_200mhz
set_interface_property irq_pps bridgedReceiverOffset ""
set_interface_property irq_pps bridgesToReceiver ""
set_interface_property irq_pps ENABLED true
set_interface_property irq_pps EXPORT_OF ""
set_interface_property irq_pps PORT_NAME_MAP ""
set_interface_property irq_pps CMSIS_SVD_VARIABLES ""
set_interface_property irq_pps SVD_ADDRESS_GROUP ""
set_interface_property irq_pps IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port irq_pps IRQ_PPS_O irq Output 1


# 
# connection point PPS_Out
# 
add_interface PPS_Out conduit end
set_interface_property PPS_Out associatedClock clock_200mhz
set_interface_property PPS_Out associatedReset rst_200mhz
set_interface_property PPS_Out ENABLED true
set_interface_property PPS_Out EXPORT_OF ""
set_interface_property PPS_Out PORT_NAME_MAP ""
set_interface_property PPS_Out CMSIS_SVD_VARIABLES ""
set_interface_property PPS_Out SVD_ADDRESS_GROUP ""
set_interface_property PPS_Out IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port PPS_Out PPS_OUT pps_out Output 1


# 
# connection point PPS_Ref
# 
add_interface PPS_Ref conduit end
set_interface_property PPS_Ref associatedClock clock_200mhz
set_interface_property PPS_Ref associatedReset rst_200mhz
set_interface_property PPS_Ref ENABLED true
set_interface_property PPS_Ref EXPORT_OF ""
set_interface_property PPS_Ref PORT_NAME_MAP ""
set_interface_property PPS_Ref CMSIS_SVD_VARIABLES ""
set_interface_property PPS_Ref SVD_ADDRESS_GROUP ""
set_interface_property PPS_Ref IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port PPS_Ref PPS_REF pps_ref Input 1


# 
# connection point time_clock
# 
add_interface time_clock conduit end
set_interface_property time_clock associatedClock clock_200mhz
set_interface_property time_clock associatedReset rst_200mhz
set_interface_property time_clock ENABLED true
set_interface_property time_clock EXPORT_OF ""
set_interface_property time_clock PORT_NAME_MAP ""
set_interface_property time_clock CMSIS_SVD_VARIABLES ""
set_interface_property time_clock SVD_ADDRESS_GROUP ""
set_interface_property time_clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port time_clock TIME_S_O time_s_o Input 32
add_interface_port time_clock TIME_NS_O time_ns_o Input 32

