# TCL File Generated by Component Editor 20.4
# Fri May 07 14:36:15 CEST 2021
# DO NOT MODIFY


# 
# SPI_ConfigFlash "SPI_ConfigFlash" v1.0
# H. ECHELARD 2021.05.07.14:36:15
# 
# 

# 
# request TCL package from ACDS 20.4
# 
package require -exact qsys 20.4


# 
# module SPI_ConfigFlash
# 
set_module_property DESCRIPTION ""
set_module_property NAME SPI_ConfigFlash
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Orolia
set_module_property AUTHOR "H. ECHELARD"
set_module_property DISPLAY_NAME SPI_ConfigFlash
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL SPI_ConfigFlash
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file SPI_ConfigFlash.vhd VHDL PATH SPI_ConfigFlash.vhd TOP_LEVEL_FILE
add_fileset_file intel_generic_serial_flash_interface_asmiblock.sv SYSTEM_VERILOG PATH intel_generic_serial_flash_interface_asmiblock.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point external
# 
add_interface external conduit end
set_interface_property external associatedClock ""
set_interface_property external associatedReset ""
set_interface_property external ENABLED true
set_interface_property external EXPORT_OF ""
set_interface_property external PORT_NAME_MAP ""
set_interface_property external CMSIS_SVD_VARIABLES ""
set_interface_property external SVD_ADDRESS_GROUP ""
set_interface_property external IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port external SCLK SCLK Input 1
add_interface_port external MISO MISO Output 1
add_interface_port external MOSI MOSI Input 1
add_interface_port external SS_n SS_n Input 1

