-- altera_jtag_fuse_access_inst.vhd

-- Generated using ACDS version 21.1 169

library IEEE;
library altera_jtag_chip_id_191;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity altera_jtag_fuse_access_inst is
	generic (
		DEVICE_FAMILY : string := "Cyclone 10 GX"
	);
	port (
		clkin      : in  std_logic                     := '0'; --  clkin.clk
		reset      : in  std_logic                     := '0'; --  reset.reset
		data_valid : out std_logic;                            -- output.valid
		chip_id    : out std_logic_vector(63 downto 0)         --       .data
	);
end entity altera_jtag_fuse_access_inst;

architecture rtl of altera_jtag_fuse_access_inst is
	component altera_jtag_chip_id_cmp is
		generic (
			DEVICE_FAMILY : string := ""
		);
		port (
			clkin      : in  std_logic                     := 'X'; -- clk
			reset      : in  std_logic                     := 'X'; -- reset
			data_valid : out std_logic;                            -- valid
			chip_id    : out std_logic_vector(63 downto 0)         -- data
		);
	end component altera_jtag_chip_id_cmp;

	for altera_jtag_fuse_access_inst : altera_jtag_chip_id_cmp
		use entity altera_jtag_chip_id_191.altera_jtag_chip_id;
begin

	device_family_check : if DEVICE_FAMILY /= "Cyclone 10 GX" generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	altera_jtag_fuse_access_inst : component altera_jtag_chip_id_cmp
		generic map (
			DEVICE_FAMILY => "Cyclone 10 GX"
		)
		port map (
			clkin      => clkin,      --  clkin.clk
			reset      => reset,      --  reset.reset
			data_valid => data_valid, -- output.valid
			chip_id    => chip_id     --       .data
		);

end architecture rtl; -- of altera_jtag_fuse_access_inst
