# TCL File Generated by Component Editor 21.1
# Tue Oct 12 07:24:41 CEST 2021
# DO NOT MODIFY


# 
# IDBoard "IDBoard" v1.0
#  2021.10.12.07:24:41
# 
# 

# 
# request TCL package from ACDS 21.1
# 
package require -exact qsys 21.1


# 
# module IDBoard
# 
set_module_property DESCRIPTION ""
set_module_property NAME IDBoard
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Orolia
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME IDBoard
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL IDBoard
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file IDBoard.vhd VHDL PATH IDBoard.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""
set_interface_property clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clk CLK_I clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset RST_I reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressGroup 0
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clk
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 bridgedAddressOffset ""
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 minimumResponseLatency 1
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 transparentBridge false
set_interface_property avalon_slave_0 waitrequestAllowance 0
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave_0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port avalon_slave_0 ADDR_I address Input 4
add_interface_port avalon_slave_0 DATA_O readdata Output 32
add_interface_port avalon_slave_0 RD_I read Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point ID_PIN
# 
add_interface ID_PIN conduit end
set_interface_property ID_PIN associatedClock ""
set_interface_property ID_PIN associatedReset ""
set_interface_property ID_PIN ENABLED true
set_interface_property ID_PIN EXPORT_OF ""
set_interface_property ID_PIN PORT_NAME_MAP ""
set_interface_property ID_PIN CMSIS_SVD_VARIABLES ""
set_interface_property ID_PIN SVD_ADDRESS_GROUP ""
set_interface_property ID_PIN IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port ID_PIN ID_PIN id_pin Input 4
add_interface_port ID_PIN ID_OSC_PIN id_osc_pin Input 4


# 
# connection point input_id
# 
add_interface input_id avalon_streaming end
set_interface_property input_id associatedClock clk
set_interface_property input_id associatedReset reset_id
set_interface_property input_id dataBitsPerSymbol 8
set_interface_property input_id errorDescriptor ""
set_interface_property input_id firstSymbolInHighOrderBits true
set_interface_property input_id maxChannel 0
set_interface_property input_id readyAllowance 0
set_interface_property input_id readyLatency 0
set_interface_property input_id ENABLED true
set_interface_property input_id EXPORT_OF ""
set_interface_property input_id PORT_NAME_MAP ""
set_interface_property input_id CMSIS_SVD_VARIABLES ""
set_interface_property input_id SVD_ADDRESS_GROUP ""
set_interface_property input_id IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port input_id data_valid valid Input 1
add_interface_port input_id chip_id data Input 64


# 
# connection point reset_id
# 
add_interface reset_id reset start
set_interface_property reset_id associatedClock clk
set_interface_property reset_id associatedDirectReset reset
set_interface_property reset_id associatedResetSinks reset
set_interface_property reset_id synchronousEdges DEASSERT
set_interface_property reset_id ENABLED true
set_interface_property reset_id EXPORT_OF ""
set_interface_property reset_id PORT_NAME_MAP ""
set_interface_property reset_id CMSIS_SVD_VARIABLES ""
set_interface_property reset_id SVD_ADDRESS_GROUP ""
set_interface_property reset_id IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_id RST_O reset Output 1

