# TCL File Generated by Component Editor 17.1
# Mon Sep 17 09:45:23 CEST 2018
# DO NOT MODIFY


# 
# Terminal_Modem "Terminal_Modem" v1.0
# H ECHELARD 2018.09.17.09:45:23
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Terminal_Modem
# 
set_module_property DESCRIPTION ""
set_module_property NAME Terminal_Modem
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Spectracom
set_module_property AUTHOR "H ECHELARD"
set_module_property DISPLAY_NAME Terminal_Modem
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Terminal_Modem
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file Terminal_Modem.vhd VHDL PATH Terminal_Modem.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point modem
# 
add_interface modem conduit end
set_interface_property modem associatedClock ""
set_interface_property modem associatedReset ""
set_interface_property modem ENABLED true
set_interface_property modem EXPORT_OF ""
set_interface_property modem PORT_NAME_MAP ""
set_interface_property modem CMSIS_SVD_VARIABLES ""
set_interface_property modem SVD_ADDRESS_GROUP ""

add_interface_port modem cts_n cts_n Output 1
add_interface_port modem dcd_n dcd_n Output 1
add_interface_port modem dsr_n dsr_n Output 1
add_interface_port modem dtr_n dtr_n Input 1
add_interface_port modem out1_n out1_n Input 1
add_interface_port modem out2_n out2_n Input 1
add_interface_port modem ri_n ri_n Output 1
add_interface_port modem rts_n rts_n Input 1

