# TCL File Generated by Component Editor 21.1
# Sat Mar 12 07:24:57 CET 2022
# DO NOT MODIFY


# 
# OpenCore_16550_UART "OpenCore 16550 UART" v1.0
#  2022.03.12.07:24:57
# 
# 

# 
# request TCL package from ACDS 21.1
# 
package require -exact qsys 21.1


# 
# module OpenCore_16550_UART
# 
set_module_property DESCRIPTION ""
set_module_property NAME OpenCore_16550_UART
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP OpenCores
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "OpenCore 16550 UART"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL gh_uart_16550_wb_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file gh_DECODE_3to8.vhd VHDL PATH gh_DECODE_3to8.vhd
add_fileset_file gh_baud_rate_gen.vhd VHDL PATH gh_baud_rate_gen.vhd
add_fileset_file gh_binary2gray.vhd VHDL PATH gh_binary2gray.vhd
add_fileset_file gh_counter_down_ce_ld_tc.vhd VHDL PATH gh_counter_down_ce_ld_tc.vhd
add_fileset_file gh_counter_integer_down.vhd VHDL PATH gh_counter_integer_down.vhd
add_fileset_file gh_edge_det.vhd VHDL PATH gh_edge_det.vhd
add_fileset_file gh_fifo_async16_rcsr_wf.vhd VHDL PATH gh_fifo_async16_rcsr_wf.vhd
add_fileset_file gh_fifo_async16_sr.vhd VHDL PATH gh_fifo_async16_sr.vhd
add_fileset_file gh_jkff.vhd VHDL PATH gh_jkff.vhd
add_fileset_file gh_parity_gen_Serial.vhd VHDL PATH gh_parity_gen_Serial.vhd
add_fileset_file gh_register_ce.vhd VHDL PATH gh_register_ce.vhd
add_fileset_file gh_shift_reg_PL_sl.vhd VHDL PATH gh_shift_reg_PL_sl.vhd
add_fileset_file gh_uart_16550.vhd VHDL PATH gh_uart_16550.vhd
add_fileset_file gh_uart_16550_wb_wrapper.vhd VHDL PATH gh_uart_16550_wb_wrapper.vhd TOP_LEVEL_FILE
add_fileset_file gh_uart_Rx_8bit.vhd VHDL PATH gh_uart_Rx_8bit.vhd
add_fileset_file gh_uart_Tx_8bit.vhd VHDL PATH gh_uart_Tx_8bit.vhd
add_fileset_file gh_counter_down_ce_ld.vhd VHDL PATH gh_counter_down_ce_ld.vhd
add_fileset_file gh_edge_det_XCD.vhd VHDL PATH gh_edge_det_XCD.vhd
add_fileset_file gh_gray2binary.vhd VHDL PATH gh_gray2binary.vhd
add_fileset_file gh_shift_reg_se_sl.vhd VHDL PATH gh_shift_reg_se_sl.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""
set_interface_property clock_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_sink wb_clk_i clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""
set_interface_property reset_sink IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_sink wb_rst_i reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressGroup 0
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave bridgedAddressOffset ""
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave minimumResponseLatency 1
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave transparentBridge false
set_interface_property avalon_slave waitrequestAllowance 0
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port avalon_slave wb_stb_i chipselect Input 1
add_interface_port avalon_slave wb_we_i write Input 1
add_interface_port avalon_slave wb_adr_i address Input 3
add_interface_port avalon_slave wb_dat_i writedata Input 32
add_interface_port avalon_slave wb_ack_o waitrequest_n Output 1
add_interface_port avalon_slave wb_dat_o readdata Output 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""
set_interface_property conduit_end IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port conduit_end sRX srx Input 1
add_interface_port conduit_end CTSn ctsn Input 1
add_interface_port conduit_end DSRn dsrn Input 1
add_interface_port conduit_end RIn rin Input 1
add_interface_port conduit_end DCDn dcdn Input 1
add_interface_port conduit_end sTX stx Output 1
add_interface_port conduit_end DTRn dtrn Output 1
add_interface_port conduit_end RTSn rtsn Output 1
add_interface_port conduit_end OUT1n out1n Output 1
add_interface_port conduit_end OUT2n out2n Output 1
add_interface_port conduit_end TXRDYn txrdyn Output 1
add_interface_port conduit_end RXRDYn rxrdyn Output 1
add_interface_port conduit_end B_CLK b_clk Output 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""
set_interface_property interrupt_sender IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port interrupt_sender IRQ irq Output 1


# 
# connection point clock_baudrate
# 
add_interface clock_baudrate clock end
set_interface_property clock_baudrate ENABLED true
set_interface_property clock_baudrate EXPORT_OF ""
set_interface_property clock_baudrate PORT_NAME_MAP ""
set_interface_property clock_baudrate CMSIS_SVD_VARIABLES ""
set_interface_property clock_baudrate SVD_ADDRESS_GROUP ""
set_interface_property clock_baudrate IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock_baudrate BR_clk clk Input 1

